# Generated by Django 5.2.7 on 2025-10-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profession',
        ),
    ]
